# Generated by Django 5.1.7 on 2025-03-11 23:10

import django.db.models.deletion
import djongo.models.fields
import eventdetails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default='https://d3vzzcunewy153.cloudfront.net/img/17f95c00-4ab0-492d-94a6-3a647e5ea2fe/570e58a0b116eea5bb29b731be15116f.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=djongo.models.fields.EmbeddedField(model_container=eventdetails.models.Location),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=djongo.models.fields.ArrayReferenceField(default='orgainzer1', on_delete=django.db.models.deletion.CASCADE, to='eventdetails.organizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=djongo.models.fields.ArrayReferenceField(default='vip', on_delete=django.db.models.deletion.CASCADE, to='eventdetails.ticket'),
            preserve_default=False,
        ),
    ]
