# Generated by Django 4.2.20 on 2025-05-16 16:02

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=255)),
                ('organizer_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('location', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('number_of_seats', models.IntegerField()),
                ('eventPhoto', models.URLField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
