# Generated by Django 4.2.20 on 2025-04-24 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventPhoto',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
