# Generated by Django 5.1.7 on 2025-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventPhoto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
