# Generated by Django 4.1.13 on 2025-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250308_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
