# Generated by Django 3.1.12 on 2025-03-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250302_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=255)),
                ('useremail', models.EmailField(max_length=254)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
