# Generated by Django 3.1.12 on 2025-03-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=255)),
                ('useremail', models.EmailField(max_length=254)),
                ('ticket_number', models.CharField(max_length=100)),
                ('purchase_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
