# Generated by Django 4.2.20 on 2025-04-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customusers_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={},
        ),
    ]
